# Generated by Django 4.1.4 on 2023-02-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('service', models.CharField(choices=[('superviseur', 'Superviseur'), ('paie', 'Paie'), ('comptabilite', 'Comptabilité'), ('informatique', 'Informatique'), ('autres', 'Autres')], max_length=50)),
                ('droits', models.CharField(blank=True, choices=[('comptabilite', 'Comptabilité'), ('paie', 'Paie'), ('direction', 'Direction')], max_length=50)),
            ],
        ),
    ]
