# Generated by Django 4.1.4 on 2023-02-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='enseignes',
            field=models.CharField(choices=[('', '------------'), ('FRANPRIX', 'FRANPRIX'), ('NATURALIA', 'NATURALIA'), ('MONOPRIX', 'MONOPRIX'), ('CARREFOUR', 'CARREFOUR'), ('AUCHAN', 'AUCHAN')], max_length=50),
        ),
    ]
