# Generated by Django 4.1.4 on 2023-02-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
