# Generated by Django 4.1.4 on 2023-02-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_magasin_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='enseignes',
            field=models.CharField(choices=[('', '------------'), ('FRANPRIX', 'FRANPRIX'), ('NATURALIA', 'NATURALIA'), ('MONOPRIX', 'MONOPRIX'), ('CARREFOUR', 'CARREFOUR'), ('AUCHAN', 'AUCHAN'), ('AUTRES', 'AUTRES')], max_length=50),
        ),
    ]
