# Generated by Django 4.1.4 on 2023-02-28 10:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_magasin_enseignes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juriste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('', '----'), ('JURISTE', 'JURISTE')], default='JURISTE', max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('DIRECTION', 'DIRECTION'), ('SUPERVISEUR', 'SUPERVISEUR'), ('COMPTABILITE', 'COMPTABILITE'), ('JURISTE', 'JURISTE'), ('PAIE', 'PAIE'), ('MAGASIN', 'MAGASIN'), ('RH', 'RH')], max_length=30, verbose_name='ROLE'),
        ),
    ]
