# Generated by Django 4.1.4 on 2023-01-07 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin_weekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('week', models.IntegerField(default=1)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='Magasin_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('day', models.DateField(default=datetime.date.today)),
                ('week', models.IntegerField(default=1)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.magasin')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
