# Generated by Django 4.1.4 on 2023-02-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin_day_value',
            name='fri',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='mon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='sat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='sun',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='thur',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='tue',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='wed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='week',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='magasin_value',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='magasin_value',
            name='week',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='magasin_weekly',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='magasin_weekly',
            name='week',
            field=models.IntegerField(default=8),
        ),
    ]
