# Generated by Django 4.1.4 on 2023-02-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin_value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='week',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='magasin_value',
            name='week',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='magasin_weekly',
            name='week',
            field=models.IntegerField(default=6),
        ),
    ]
