# Generated by Django 4.1.4 on 2023-02-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magboard', '0004_alter_magasin_day_value_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin_day_value',
            name='week',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='magasin_value',
            name='week',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='magasin_weekly',
            name='week',
            field=models.IntegerField(default=9),
        ),
    ]
