# Generated by Django 4.1.4 on 2023-01-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magboard', '0004_alter_magasin_day_value_fri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin_day_value',
            name='fri',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='mon',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='sat',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='sun',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='thur',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='tue',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='magasin_day_value',
            name='wed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
