# Generated by Django 4.1.4 on 2023-03-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magboard', '0002_alter_magasin_day_value_fri_and_more'),
        ('magboard', '0005_alter_magasin_day_value_week_and_more'),
    ]

    operations = [
    ]
